### ISSUE TITLE
Invalid reference in setu/schemas/2020-01/AssignmentAdditionalNL.xsd

### ISSUE THREAD

**Issue by basmul** [setu-standards/xml-specifications#1]
Just a very minor issue and a quick fix.

Line 13: 
`<xsd:import namespace="http://ns.hr-xml.org/2007-04-15" schemaLocation="../../../hr-xml/SIDES/Assignment"/>`

Should be

`<xsd:import namespace="http://ns.hr-xml.org/2007-04-15" schemaLocation="../../../hr-xml/SIDES/Assignment.xsd"/>`

Regards,
Bas

**Comment by RobinTNO** [comment]
Thanks Bas. We have reorganized the whole file path structure. I think this is a small left over mistake from that. I've changed it.
